travelpayout:
  token: "${TOKEN:bdd5ddc926ca9d51e9a35700060d1fd0}"
  url: "${TRAVEL_PAYOUT_URL:api.travelpayouts.com}"
  search-path: "/v2/prices/latest"
  countries-path: "/aviasales_resources/v3/countries.json"
  cities-path: "/aviasales_resources/v3/cities.json"
  airports-path: "/aviasales_resources/v3/airports.json"

spring:
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/flightsearcher
    username: postgres
    password: postgres
    hikari:
      schema: flight_fix
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
